### ISSUE TITLE
Make timeline by date instead of case number

### ISSUE THREAD

**Issue by tschmidt23** [CSE512-15S/a3-jbare-sonyaa-tws10#17]
It would be nice to show years on the left instead of arbitrary case numbers.

Sonya, I assigned you because it looks like you already know how to do this?

**Comment by sonyaa** [comment]
Do you want the axis and the ticks to remain the same, just replace the labels with the corresponding year?

**Comment by tschmidt23** [comment]
It would be nice to have unevenly spaced ticks for the start of each year, but I'm not sure if that's possible.

**Comment by sonyaa** [comment]
Anything is possible! I did that (e6678fb20a55805f4463370b77e2e7f214b87afd) but I'm not sure that's what we want - you can already see that they overlap, and if we pull in the data from all years, it's gonna be pretty bad. Maybe 10 evenly spaced labels is better - with the year on them. Since there's a lot of years and only 10 labels, the years won't be repeated.

**Comment by tschmidt23** [comment]
Awesome! 

For the spacing thing, could we just do a label for every 5 years then? Or more generally every N where N is a parameter we can set such that it looks good when we load all the data?

**Comment by sonyaa** [comment]
Done in 1b020884eb43f431a05b4797ee69af6ff1108dc1. Use tickPeriod to set the N.
